# 基本操作

In [1]:
import torch

张量表示一个由数值组成的数组，这个数组可能有多个维度

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

访问张量的形状：shape

In [4]:
x.shape

torch.Size([12])

元素数量：numel(), num of elements, 返回一个标量

In [5]:
x.numel()

12

改变张量形状 reshape()

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

torch.zeros((形状))

In [10]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

运算：+, -, *, /, **
这些运算都是按**元素**进行的

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素应用更多计算

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量拼接 torch.cat((), dim= )  dim=0按行往下拼接，dim=1按列向后拼接

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算法构建二维张量

In [20]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中所有元素求和

In [21]:
X.sum()

tensor(66.)

即使形状不同，仍然可以广播，容易出错！需要注意

In [23]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

元素访问

In [27]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

赋值

In [30]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋相同的值

In [31]:
X[0:2,:]

tensor([[0., 1., 2., 3.],
        [4., 5., 9., 7.]])

In [32]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [40]:
before = id(Y) # id() 获取变量唯一的地址
Y = Y+X  # Y += X 则是原地操作，结果是True，这个和Y[:] = Y+X 效果一样
 # 结果是False，这个新的Y和原来的Y地址是不同的，原来的已经析构掉了
before, id(Y), id(Y) == before

(2342815534992, 2342815534992, True)

执行原地操作

In [39]:
Z = torch.zeros_like(Y) # zeros_like() 创建一个和Y的shape，数据类型一样的都是1的张量
print('id(Z)', id(Z))
Z[:] = X+Y # 通过 [:] 逐元素赋值
print('id(Z)', id(Z))

id(Z) 2342815534832
id(Z) 2342815534832


In [41]:
before = id(X)
X += Y
id(X) == before # 结果是True，X[:] = X+Y 或X += Y都是原地操作

True

转换为Numpy张量

In [84]:
A = X.numpy()

B = torch.tensor(A)
A, type(A), B, type(B)

(array([[62., 61., 64., 63.],
        [61., 62., 63., 64.],
        [44., 48., 52., 56.]], dtype=float32),
 numpy.ndarray,
 tensor([[62., 61., 64., 63.],
         [61., 62., 63., 64.],
         [44., 48., 52., 56.]]),
 torch.Tensor)

将大小为1的张量转换为python 标量

In [43]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 数据预处理

处理csv文件

In [50]:
import os
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write(f'NA,Pave,127500\n')
    f.write(f'2,NA,106000\n')
    f.write(f'4,NA,178100\n')
    f.write(f'NA,NA,140000\n')
print(data_file)

.\data\house_tiny.csv


In [53]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


为了处理缺失数据，典型方法包括：插值、删除，这里我们考虑插值

In [70]:
# iloc:index location
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs)
print(outputs)
inputs = inputs.fillna(inputs.mean(numeric_only=True)) # 计算mean时numeric_only忽略非数值
# 将平均数填充到NAN中
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于非数值，缺失的可以当做一个类别

In [68]:
print(pd.get_dummies(inputs))

   NumRooms  Alley_Pave
0       3.0        True
1       2.0       False
2       4.0       False
3       3.0       False


In [77]:
# dummy_na=True表示将nan也当做一个类
inputs = pd.get_dummies(inputs, dummy_na=True) 
print(inputs)
print(inputs.values)
type(inputs), type(inputs.values)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True
[[3.0 True False]
 [2.0 False True]
 [4.0 False True]
 [3.0 False True]]


(pandas.core.frame.DataFrame, numpy.ndarray)

现在将所有的条目都变成了数值类型，可以转换为张量格式了

In [88]:
import torch
import numpy as np
# 64位浮点数计算比较慢，所以一般用float32
X, y= torch.tensor(inputs.to_numpy(dtype=np.float32)), torch.tensor(outputs.to_numpy(dtype=np.float32))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([127500., 106000., 178100., 140000.]))