In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

向量

In [5]:
x = torch.arange(4)
x, x[3]

(tensor([0, 1, 2, 3]), tensor(3))

In [6]:
len(x)

4

In [8]:
x.shape

torch.Size([4])

矩阵

In [9]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
A.T # 转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B ==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

向量是标量的推广，矩阵是向量的推广，我们可以构建更多轴（维度）的数据结构

In [14]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [17]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()  # 深拷贝，分配新的内存
B[0,0] = 2
A, A+B, A

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 2.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

矩阵按元素乘法 哈达玛积(Hadamard product) 符号： ⊙

In [18]:
B[0,0] = 0
A*B  # 

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [24]:
A@B # 矩阵乘法

torch.Size([2, 5, 4])

In [20]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a+X, (a*X).shape # 对所有元素都加a，对所有元素都乘a

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [21]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [33]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

按某一维度求和

In [34]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [35]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [36]:
A.sum(axis=[0, 1]), A.sum(axis=[0, 1]).shape

(tensor([180., 190., 200., 210.]), torch.Size([4]))

相关计算

In [40]:
A.mean(), A.sum() / A.numel(), A.numel()# A.numel()A一共多少个元素

(tensor(19.5000), tensor(19.5000), 40, 2)

In [41]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

如果希望求和或均值时，维度不变，避免计算sum，mean()直接丢掉计算的维度

In [47]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A, sum_A.shape, A.sum(axis=1), A.sum(axis=1).shape

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

通过广播将A除以sum_A, A和sum_A维度必须一样

In [50]:
A, A/sum_A

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
          [0.1000, 0.1111, 0.1200, 0.1273],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.3000, 0.2889, 0.2800, 0.2727],
          [0.4000, 0.3778, 0.3600, 0.3455]],
 
         [[0.1429, 0.1448, 0.1467, 0.1484],
          [0.1714, 0.1724, 0.1733, 0.1742],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.2286, 0.2276, 0.2267, 0.2258],
          [0.2571, 0.2552, 0.2533, 0.2516]]]))

某个轴计算A元素的累加求和

In [53]:
(A, A.cumsum(axis=0)) # 按第0个维度累加

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]))

向量点积

In [56]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

等价于按元素乘法，再求和

In [61]:
torch.sum(x * y)

tensor(6.)

矩阵乘向量 Ax, 相当于a的第i行与x点积

In [62]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A.shape, x.shape, torch.mv(A,x), A@x

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵乘法

In [63]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [65]:
B = torch.ones(4, 3)
torch.mm(A, B), A@B

(tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

L2范数：向量或矩阵的长度，是元素平方和开根号

In [66]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # (3^2 + 4^2)开根号

tensor(5.)

L1范数：每个元素绝对值之和

In [67]:
torch.abs(u).sum() # 3 + 4

tensor(7.)

矩阵 弗罗贝尼乌斯范数(Frobenius norm) 也叫F范数 F-norm

是矩阵元素的平方和开根号。 和向量的L2 norm实际上一样

In [69]:
torch.ones((4, 9)) , torch.norm(torch.ones((4, 9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))